### ISSUE TITLE
xeditor features todo list

### ISSUE THREAD

**Issue by tzaiyang** [tzaiyang/xeditor#1]
# Requirements

- Features
  - 实现 CommonMark 和 GFM 规范
  - 大纲，数学公式
  - 全局搜索内容，全局搜索文件名
  - 支持[toc]语法
  - Diagram
    - [ ] [mermaid](https://mermaid-js.github.io/mermaid)(支持嵌入[Font-Awesome icons](https://github.com/FortAwesome/Font-Awesome))
    - [ ] [mindmap](https://github.com/gera2ld/markmap)
    - [ ] [draw.io](https://github.com/jgraph/drawio)(支持直接[mxGraphModel](https://github.com/jgraph/mxgraph)渲染，或draw.io文件链接渲染)
    - [ ] [graphviz](https://graphviz.org/)
    - [ ] [abcjs](https://github.com/paulrosen/abcjs)
    - [ ] [Wavedrom](https://github.com/wavedrom/wavedrom)
  - Table
      - [ ] 支持行与列的增删
      - [ ] 支持表内连接跳转
      - [ ] 可拖拽行列顺序
  - 自动识别链接，高亮可跳转
- 实现上
  - Open Source
  - 拒绝专有格式，一侓markdown
  - 语法上尽量与同类软件保持兼容
  - WYSIWYG（所见即所得，实时渲染，同时支持Split View源码模式）
  - 插件化，可扩展，且支持用户跟进插件最新版，如mermaid最新版
  - 跨平台（Windows, macOS, Linux，Android, iOS），至少是桌面端跨平台
  - 快捷键（参照typora）

## 技术选型

- [TypeScript](https://www.typescriptlang.org/)
- [Electron](https://www.electronjs.org/)

# References

1. https://github.com/purocean/yn
2. https://github.com/Vanessa219/vditor
3. https://github.com/88250/lute
4. https://github.com/marktext/marktext
5. https://github.com/benweet/stackedit
6. https://github.com/nhn/tui.editor
7. https://github.com/pandao/editor.md
8. https://github.com/MacDownApp/macdown
9. https://github.com/vnotex/vnote
10. https://github.com/microsoft/vscode
11. 社区给typora提的diagram的需求：https://github.com/typora/typora-issues/issues/1138

**Comment by YuQiao0303** [comment]
666

**Comment by tzaiyang** [comment]
> 666

哈哈哈，还没开干呢就666了，欢迎提需求！ @YuQiao0303
